Refactor connectivity checks in build workflow for clarity

diff --git a/.github/workflows/build-web.yml b/.github/workflows/build-web.yml
--- a/.github/workflows/build-web.yml
+++ b/.github/workflows/build-web.yml
@@ -17,10 +17,13 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v4
 
-      - name: Check connectivity
-        run: |
-        ping -c 3 wpilib.jfrog.io || echo "Cannot reach wpilib.jfrog.io"
-        curl -I https://repo.lux-robotic.dev/simple/ || echo "Cannot reach lux-robotic.dev"
+      - name: Check connectivity frog
+        run: ping -c 3 wpilib.jfrog.io || echo "Cannot reach wpilib.jfrog.io"
+        
+
+      - name: Check connectivity frog
+        run: curl -I https://repo.lux-robotic.dev/simple/ || echo "Cannot reach lux-robotic.dev"
+
 
       - name: Build Project
         run: just package
